### ISSUE TITLE
Increase bytes of a memorylocation.

### ISSUE THREAD

**Issue by zhongpipi** [pylessard/python-udsoncan#144] opened 2023-01-12 13:12 UTC
udsoncan/__init__.py  class AddressAndLengthFormatIdentifier.
Can we increase more possible values of memsize_map? Like 
{
            8 : 1,
            16 : 2,
            24 : 3,
            32 : 4,
            40 : 5
    }

**Comment by zhongpipi** [comment] 2023-01-12 13:39
Hi, after updating to version 1.6, this issue has been solved. 
Thank you so much for developing UDSonCAN library! !

**Comment by pylessard** [comment] 2023-01-12 14:15
Thank you 
Indeed a duplicate of #140

**Closed by pylessard** 2023-01-12 14:15 UTC
