### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by pompushko** [pylessard/python-udsoncan#200] opened 2024-01-22 15:01 UTC
Hello

I use IsoTPSocketConnection for own project. My CanBus speed is 500kb\s

When I trying to make some tests with one request from ECU, I have such speed
`100%|###########################################| 100 of 100 Time:  0:00:00 107.7 it/s`

`response = client.read_data_by_identifier(0x1000)`

![image](https://github.com/pylessard/python-udsoncan/assets/20593903/804f00b7-f535-4cc9-b86e-ed6d6b6b6be9)

![image](https://github.com/pylessard/python-udsoncan/assets/20593903/aa858ad6-dfd9-4623-b936-6bdc766c6550)

With PythonIsoTpConnection too slow :D

![image](https://github.com/pylessard/python-udsoncan/assets/20593903/b4d4ca5c-bf61-4cfa-9348-f0119b061735)

But with cangen I can load almost fully my CAN-bus:
![image](https://github.com/pylessard/python-udsoncan/assets/20593903/298469c6-1118-4127-8e35-57802fadf746)

Main question, is that possible to make faster transmission? As I know, Python is limited by 1 code only. But I have 4. I tried to compile my test app with Cython to use all my CPU and that didn't helped me :)

Thank you

**Comment by pylessard** [comment] 2024-01-23 02:28
Download latest isotp package (v2.0.3)
Update udsoncan to 1.21.1    (1.21.2 will release soon)

You should get an improvement

**Comment by pylessard** [comment] 2024-01-23 02:57
Just so you know, when you'll update udsoncan, make sure to pass an ``isotp.Address`` if you use the ``IsotpSocketConnection``. IT is now required. See https://udsoncan.readthedocs.io/en/latest/udsoncan/questions_answers.html#my-isotpsocketconnection-raises-an-error-after-updating-udsoncan

**Comment by pompushko** [comment] 2024-01-23 18:20
> Just so you know, when you'll update udsoncan, make sure to pass an `isotp.Address` if you use the `IsotpSocketConnection`. IT is now required. See https://udsoncan.readthedocs.io/en/latest/udsoncan/questions_answers.html#my-isotpsocketconnection-raises-an-error-after-updating-udsoncan

Well, This is strange, I have this code:
`    conn = IsoTPSocketConnection(args.interface, isotp.Address(isotp.AddressingMode.NormalFixed_29bits, rxid=0xF1, txid=args.ecuaddress), tpsock=tpsock)`

And I still get:
`RuntimeError: Provide an isotp.Address to the IsoTPSocketConnection. The interface has changed in a non-backward compatible way and this is now required.`

**Comment by pylessard** [comment] 2024-01-23 19:30
Are you sure this line raise the issue. check your stack trace.
![image](https://github.com/pylessard/python-udsoncan/assets/2386969/76b78559-ace6-44f5-9915-e1f0ec8d03c8)

**Comment by pompushko** [comment] 2024-01-23 20:03
Well.... Yes 
95 line...


![image](https://github.com/pylessard/python-udsoncan/assets/20593903/3dcf9b6c-ceef-42f1-b743-597b88e2ac8f)

![image](https://github.com/pylessard/python-udsoncan/assets/20593903/02174424-f25a-437e-911f-2252759b1924)

**Comment by pylessard** [comment] 2024-01-24 02:52
I don't know what to say. Something else is going on. The test condition is quite straight forward, I even have unit test that validates it.

print kwargs inside the IsotpSocketConenction constructor please.

**Comment by pompushko** [comment] 2024-01-24 09:17
> I don't know what to say. Something else is going on. The test condition is quite straight forward, I even have unit test that validates it.
> 
> print kwargs inside the IsotpSocketConenction constructor please.

Could you, please,  tell me how to do that?
Thank you

**Comment by pylessard** [comment] 2024-01-24 13:13
edit the file defining `IsotpSocketConnection `.  You can find it by looking at ``udsoncan.connections.__file__``

then do ``print(kwargs)`` inside of  ``__init__``

**Comment by pompushko** [comment] 2024-01-24 15:54
Hehe...


```
{'rxid': 32, 'txid': 241}
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "udstest/uds.py", line 95, in udstest.uds.main
  File "/home/flasher/.local/lib/python3.11/site-packages/udsoncan/connections.py", line 306, in __init__
    raise RuntimeError(
RuntimeError: Provide an isotp.Address to the IsoTPSocketConnection. The interface has changed in a non-backward compatible way and this is now required.
```

**Comment by pompushko** [comment] 2024-01-24 16:05
Well. I found the problem. 

But, my tests give me same performance :(

**Comment by pylessard** [comment] 2024-01-24 16:41
What do you pass to PythonIsoTPConnection?   Try a notifierBasedCanStack.

**Comment by pompushko** [comment] 2024-01-24 16:43
I use IsotpSocketConnection , not PythonIsoTPConnection

**Comment by pylessard** [comment] 2024-01-24 17:34
You opened an issue saying that the PythonIsotpConnection was slower than IsoTPSocketConenction.

What are you asking?

**Comment by pompushko** [comment] 2024-01-24 17:36
Im asking, is that possible to use all CPU cores when using IsoTPSocketConnection or PythonIsoTpConnection. Or make faster transmission...

**Comment by pylessard** [comment] 2024-01-24 20:11
Using more CPU cores will not give you a faster transmission. The bottleneck is not the CPU.

To have a faster transmission, start by identifying the cause of the slowness. IsoTP protocol has some timing parameter that can be adjusted. Most likely that the receiving party is requiring the sender to not go too fast.   

Start by sharing a can log of a transmission and indicate what you consider slow.

**Comment by pylessard** [comment] 2024-01-30 14:41
Closing this issue. reopen if needed

**Closed by pylessard** 2024-01-30 14:41 UTC
